### PR TITLE
Sounds using VPK

### PR DESCRIPTION
**Pull request by c-128**
Had the shower thought to have sounds from the INFRA OST. To hopefully avoid legal issues, this works by checking if INFRA is installed on the computer. If so, it uses https://github.com/ValvePython/vpk to extract the VPK file with the sounds and then plays it back. However I am unsure if this is a good idea with text-based games.

### CODE REVIEW

**Comment by eetnaviation** [comment]
I'm liking the idea! I will take a look at it. But yeah not sure if adding sounds to a text based game is good. Might make 2 releases: no sound and sound.

**Comment by eetnaviation** [comment]
Would it be possible to add action-sound-effects? Like interacting with a breaker will have the breaker-use sound effect?

**Comment by c-128** [comment]
Yes if I remember right, the same VPK file contains sounds for that. Also, I personally think that sound can be an option.

**Comment by eetnaviation** [comment]
This currently seens like the best option:

1. No sounds
2. With sounds

Users can choose on the beginning of the game (probably in a menu) if they want sound or no sound.

**Comment by c-128** [comment]
Small missclick, but need to agree with you

**Comment by c-128** [comment]
Implemented, closing for now

**Pull request closed without merging**
